[package]
name = "foldermirror"
version = "1.0.0"
authors = ["Lupascu Gabriel Cristian <lupascugabrielcristian@gmail.com>"]
edition = "2021"

[[bin]]
name = "foldermirror"
path = "foldermirror.rs"

[dependencies]
quick-xml = "0.26.0"



